ZONENAME = "name"
DESC = "desc"
EXAM = "exam"
NORTH = "north"
SOUTH = "south"
WEST = "west"
EAST = "east"
UTOS = False

#MAP
zonemap = {
        'a1': {
            ZONENAME: 'Construction Supply Store',
            DESC: 'A place where you can buy construction materials and tools.',
            EXAM: 'may rugby sa shelves.',
            NORTH: '', 
            SOUTH: 'b1', 
            WEST: '', 
            EAST: 'a2', 
        },
        'a2': {
            ZONENAME: 'Tattoo Parlor',
            DESC: 'A place where you can get tattoos done.',
            EXAM: 'may nagru-rugby sa gilid ng parlor.',
            NORTH: '', 
            SOUTH: 'b2', 
            WEST: 'a1', 
            EAST: 'a3', 
        },
        'a3': {
            ZONENAME: 'Bahay ni Tita',
            DESC: 'Bahay ng tita mo na may maliit na farm sa gilid.',
            EXAM: 'sinisenyasan ka ng tita mo na lumapit ka sa kanya. Uutusan ka yata.',
            NORTH: '', 
            SOUTH: 'b3', 
            WEST: 'a2', 
            EAST: 'a4', 
        },
        'a4': {
            ZONENAME: 'Church',
            DESC: 'A place of worship where you can pray and reflect.',
            EXAM: 'may krus sa altar.',
            NORTH: '', 
            SOUTH: 'b4', 
            WEST: 'a3', 
            EAST: 'a5', 
        },
        'a5': {
            ZONENAME: 'Encantondo Hill',
            DESC: 'A scenic hill with a beautiful view of the town (tambak ng buhangin at bato).',
            EXAM: 'madulas ang daan papunta sa tuktok ng burol. Sarap paring puntahan ng tuktok',
            NORTH: '', 
            SOUTH: 'b5', 
            WEST: 'a4', 
            EAST: '', 
        },
        'b1': {
            ZONENAME: 'Motorcycle Dealership',
            DESC: 'A place where you can buy and repair motorcycles.',
            EXAM: 'may motor na naka-stored sa loob ng tindahan.',
            NORTH: 'a1', 
            SOUTH: 'c1', 
            WEST: '', 
            EAST: 'b2', 
        },
        'b2': {
            ZONENAME: 'Encantondo Daycare Center',
            DESC: 'A place where children are cared for during the day.',
            EXAM: 'may mga teacher na nagtuturo sa loob ng daycare center.',
            NORTH: 'a2', 
            SOUTH: 'c2', 
            WEST: 'b1', 
            EAST: 'b3', 
        },
        'b3': {
            ZONENAME: 'Encantondo Covered Court',
            DESC: 'A covered court where people can gather and play.',
            EXAM: 'tao na masasama ang tingin sa iyo sa labas ng court',
            NORTH: 'a3', 
            SOUTH: 'c3', 
            WEST: 'b2', 
            EAST: 'b4', 
        },
        'b4': {
            ZONENAME: 'BDO',
            DESC: 'A bank where you can deposit and withdraw money.',
            EXAM: 'may tao na naglalakad sa labas ng BDO. May hawak ng wallet ang isa sa kanila.',
            NORTH: 'a4', 
            SOUTH: 'c4', 
            WEST: 'b3', 
            EAST: 'b5', 
        },
        'b5': {
            ZONENAME: 'Dali Store',
            DESC: 'A small store where you can buy snacks and drinks.',
            EXAM: 'may freezer sa loob ng tindahan. Mukhang may yelo silang tinda.',
            NORTH: 'a5', 
            SOUTH: 'c5', 
            WEST: 'b4', 
            EAST: '', 
        },
        'c1': {
            ZONENAME: 'Naka-park na E-Bike sa Daan',
            DESC: 'Kapal, buong bike nakaparking sa kalahati ng kalsada.',
            EXAM: 'walang tow truck na papunta, sayang.',
            NORTH: 'b1', 
            SOUTH: 'd1', 
            WEST: '', 
            EAST: 'c2', 
        },
        'c2': {
            ZONENAME: 'Encantondo Plaza',
            DESC: 'A bustling plaza where people gather and socialize.',
            EXAM: 'may stall sa paligid ng plaza. Mukhang may mga pagkain at inumin na binebenta roon.',
            NORTH: 'b2', 
            SOUTH: 'd2', 
            WEST: 'c1', 
            EAST: 'c3', 
        },
        'c3': {
            ZONENAME: 'Encontondo University',
            DESC: 'A prestigious university where students come to learn and grow.',
            EXAM: 'ang leader mo sa final project na sinisenyasan ka. Mukhang may sasabihin yata sa iyo.',
            NORTH: 'b3', 
            SOUTH: 'd3', 
            WEST: 'c2', 
            EAST: 'c4', 
        },
        'c4': {
            ZONENAME: 'Encantondo Police Station',
            DESC: 'A police station where law enforcement officers are stationed.',
            EXAM: 'minumukhaan ka nila. Mukhang may nagawa kang mali.',
            NORTH: 'b4', 
            SOUTH: 'd4', 
            WEST: 'c3', 
            EAST: 'c5', 
        },
        'c5': {
            ZONENAME: 'Mr. Donuts',
            DESC: 'A small donut shop where you can buy fresh donuts.',
            EXAM: 'may butternut, favourite flavour ni crush.',
            NORTH: 'b5', 
            SOUTH: 'd5', 
            WEST: 'c4', 
            EAST: '', 
        },
        'd1': {
            ZONENAME: 'Bigbrew Coffee Shop',
            DESC: 'A cozy coffee shop where you can enjoy a good cup of coffee.',
            EXAM: 'problemado ang bantay sa coffee shop, mukhang kinukulang sila ng sangkap',
            NORTH: 'c1', 
            SOUTH: 'e1', 
            WEST: '', 
            EAST: 'd2', 
        },
        'd2': {
            ZONENAME: 'Novo',
            DESC: 'A small market where you can buy various items.',
            EXAM: 'masama ang tingin sa iyo nung isang lalaki sa tapat ng store.',
            NORTH: 'c2', 
            SOUTH: 'e2', 
            WEST: 'd1', 
            EAST: 'd3', 
        },
        'd3': {
            ZONENAME: 'Encantondo Doctors',
            DESC: 'A medical clinic where you can receive healthcare services.',
            EXAM: 'mukhang amoy alcohol sa tapat ng hospital.',
            NORTH: 'c3', 
            SOUTH: 'e3', 
            WEST: 'd2', 
            EAST: 'd4', 
        },
        'd4': {
            ZONENAME: 'Pandayan Bookstore',
            DESC: 'A bookstore where you can buy various books.',
            EXAM: 'may bond paper sa loob ng bookstore.',
            NORTH: 'c4', 
            SOUTH: 'e4', 
            WEST: 'd3', 
            EAST: 'd5', 
        },
        'd5': {
            ZONENAME: 'Bakal Gym',
            DESC: 'A place where you can exercise and stay fit.',
            EXAM: 'pamilyar sa iyo ang bantay ng gym.',
            NORTH: 'c5', 
            SOUTH: 'e5', 
            WEST: 'd4', 
            EAST: '', 
        },
        'e1': {
            ZONENAME: 'Encantondo Seaside',
            DESC: 'A beautiful seaside where you can relax and enjoy the view (kanal na punong-puno ng basura).',
            EXAM: 'mukhang mabaho. May kademonyohan kang nasa isip.',
            NORTH: 'd1', 
            SOUTH: '', 
            WEST: '', 
            EAST: 'e2', 
        },
        'e2': {
            ZONENAME: 'Bahay na Violet',
            DESC: 'A cozy house and bahay ni crush.',
            EXAM: 'nakatambay si crush sa biranda ng bahay nila. Mukhang may ginagawa siya sa cellphone niya.',
            NORTH: 'd2', 
            SOUTH: '', 
            WEST: 'e1', 
            EAST: 'e3', 
        },
        'e3': {
            ZONENAME: 'Bahay na Green',
            DESC: 'A cozy house and bahay ng tropa mo.',
            EXAM: 'ang tropa mo na kasama ang ea niya. Mukhang may ibubulong yata sa iyo ang tropa mo.',
            NORTH: 'd3', 
            SOUTH: '', 
            WEST: 'e2', 
            EAST: 'e4', 
        },
        'e4': {
            ZONENAME: 'Home',
            DESC: 'Your humble abode where you can rest and recover.',
            EXAM: 'may sinasabi ang nanay mo, uutusan ka yata sa bahay.',
            NORTH: 'd4', 
            SOUTH: '', 
            WEST: 'e3', 
            EAST: 'e5', 
            UTOS: False
        },
        'e5': {
            ZONENAME: 'Encantondo Town Hall',
            DESC: 'The local government building where you can handle various administrative tasks.',
            EXAM: 'masama ang tingin sa iyo nung isang tanod, mukhang may nagawa kang mali.',
            NORTH: 'd5', 
            SOUTH: '', 
            WEST: 'e4', 
            EAST: '', 
        }
    }